name: "rekrut"

services:
  front:
    build:
      context: ./
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules  # éviter de monter node_modules local
    ports:
      - "8100:8100"
    command: ionic serve --external
